Added certificate chain to generated certificates
icecave/honeycomb pull request #40
Opened 2018-10-17 04:30 UTC by koshatul

Adds the certificate chain to the TLS connection.

2018-10-17 23:58 UTC, jmalloc requested changes

2018-10-17 23:58 UTC, jmalloc commented on Makefile
> +docker: artifacts/docker-$(DOCKER_TAG).touch artifacts/build/release/linux/amd64/healthcheck artifacts/build/release/linux/amd64/honeycomb
These dependencies are already specified here

https://github.com/icecave/honeycomb/blob/master/Makefile#L102

2018-10-17 23:58 UTC, jmalloc commented on Makefile
> +MATRIX_ARCH ?= amd64
IIRC This should not be necessary because a release build does not target Darwin, only Linux (handled by docker deps)

2018-10-18 04:29 UTC, koshatul commented
Updated to remove changes to `Makefile`.

It wasn't building so I had made some changes to get it working.

2018-10-18 04:34 UTC, merged