Add an optional ACME certificate provider.
icecave/honeycomb pull request #54
Opened 2019-09-23 04:42 UTC by jmalloc

2019-09-26 04:23 UTC, jmalloc commented
As far as I know, right at this moment, the code is "complete", but I will need to do further testing in the company sandbox next week.

2019-09-27 04:10 UTC, ezzatron reviewed
I only gave it a quick scan, but seems logical 👍

2019-09-27 04:10 UTC, ezzatron commented on src/cmd/honeycomb/certs.go
> +// fileCertificateProvider returns a cert provider that obtains certificates
Should be `acmeCertificateProvider`?

2019-09-30 00:00 UTC, koshatul commented
I think I've said it before, I'm a huge fan of the `.next()` style of ordering processors instead of using a slice of them.

Other than that I'd need to sit down and read through a lot of changes :)

2019-09-30 00:01 UTC, jmalloc commented
Yeah, it's pretty involved.  And I can say right now, that it doesn't work :P

2019-09-30 00:03 UTC, jmalloc commented
> I think I've said it before, I'm a huge fan of the `.next()` style of ordering processors instead of using a slice of them.

I use that approach when implementing middlewares - things that can conditionally forward onto the "next stage".

In this case, it's a priority ordered list, it doesn't make sense for each implementation to know about the others. They can also appear in multiple lists with different priorities, meaning conceptually there are different "next" providers to try depending on other factors (whether or not the domain is recognised).

2019-10-10 02:41 UTC, koshatul requested changes
just the `from from`, everything else looks OK, I might need to check out the branch to actually follow the new code though.

2019-10-10 02:41 UTC, koshatul commented on src/frontend/cert/file_provider.go
> +				"Loaded certificate %s from from '%s'",
`from from`

2021-12-06 06:36 UTC, closed without merging